<?php
/**
 *Copyright 2008, Jefferson González (JegoYalu.com)
 *This file is part of Jaris CMS and licensed under the GPL,
 *check the license.txt file for version and details or visit
 *http://www.gnu.org/licenses/gpl.html.
 * 
 *@file Jaris CMS module info file
 *
 *@note You always need to create an info.php file for your modules.
 */

$module["name"] = "Visits Counter";
$module["description"] = "Logs the visits to your website and presents you various details about it.";
$module["namespace"] = "Visits";
$module["version"] = "1.5.3";
$module["author"] = "Jefferson González";
$module["email"] = "jgonzalez@jegoyalu.com";
$module["website"] = "http://www.jegoyalu.com";

$module["dependencies"][] = "ipinfo";


/**

Version 1.5.3 - Date 26/11/2012

    * Added SQLite\Turbo to database insertions.

Version 1.5.2 - Date 13/06/2012

    * Visit database is now generated by year to keep good performance when accessing it
    * Compatibility with previous version using only 1 database to store database has
      ben kept in order to correctly retrieve data for previous years using the visits db 

Version 1.5.1 - Date 18/04/2012

    * Added rawurldecode to referral query to correctly display it on daily visits

Version 1.5 - Date 23/02/2011

    * Fixed admin/visits/daily navigation
    * Fixed admin/visits/visitor viewed pages order

Version 1.4 - Date 23/11/2010

    * Fixed most viewed pages count (not perfect solution but works)

Version 1.3 - Date 15/06/2010

    * Fixed set group permissions hook name that wasnt being called because of wrong name (typo)

Version 1.2 - Date 15/06/2010

    * Added index to all tables
    * Fixed most viewed pages
    * Most viewed pages from text to integer
    * Added more tabs for easy navigation

*/

?>
