<?php
/**
 *Copyright 2008, Jefferson González (JegoYalu.com)
 *This file is part of Jaris CMS and licensed under the GPL,
 *check the license.txt file for version and details or visit
 *http://www.gnu.org/licenses/gpl.html.
 *
 *@file Database file that stores the site settings management page.
 */

//For security the file content is skipped from the world eyes :)
exit;
?>

row: 0
    field: title
        <?php print t("Upload Sqlite Backup") ?>
    field;

    field: content
        <?php

            JarisCMS\Security\ProtectPage(array("edit_settings"));
            
            
            if(!isset($_REQUEST["btnUpload"]) && !isset($_REQUEST["btnCancel"]))
            {
                JarisCMS\System\AddMessage(t("By uploading a backup you will overwrite any existing data on a database."), t("Warning"));
            }

            if(isset($_REQUEST["btnUpload"]))
            {
                if("" . stristr($_FILES["backup_file"]["type"], "zip") . "" != "")
                {
                    if(class_exists("ZipArchive"))
                    {                        
                        $zip = new ZipArchive;
                        $zip->open($_FILES["backup_file"]["tmp_name"]);
                        $fp = $zip->getStream($zip->getNameIndex(0));    
                                            
                        JarisCMS\SQLite\Restore(JarisCMS\FileSystem\StripFileExtension($_FILES["backup_file"]["name"]), $fp);
                        
                        fclose($fp);
                        
                        $zip->close();
                    }
                }
                else
                {
                    $fp = fopen($_FILES["backup_file"]["tmp_name"], "r");
                    
                    JarisCMS\SQLite\Restore(JarisCMS\FileSystem\StripFileExtension($_FILES["backup_file"]["name"]), $fp);
                }
                
                if(filesize(JarisCMS\Setting\GetDataDirectory() . "sqlite/" . JarisCMS\FileSystem\StripFileExtension($_FILES["backup_file"]["name"])) > 0)
                {
                    JarisCMS\System\AddMessage(t("Database restored."));
                }
                else
                {
                    JarisCMS\System\AddMessage(t("Database could not be restored"), "error");
                }

                JarisCMS\System\GoToPage("admin/settings/sqlite");
            }
            elseif(isset($_REQUEST["btnCancel"]))
            {
                JarisCMS\System\GoToPage("admin/settings/sqlite");
            }
            
            $parameters["name"] = "sqlite-upload";
            $parameters["class"] = "sqlite-upload";
            $parameters["action"] = JarisCMS\URI\PrintURL("admin/settings/sqlite/upload");
            $parameters["method"] = "post";
            $parameters["enctype"] = "multipart/form-data";
            
            $fields[] = array("type"=>"file", "label"=>t("Backup file:"), "name"=>"backup_file", "id"=>"backup_file", "description"=>t("An sql or zip backup file generated by the sqlite backup center."));

            $fields[] = array("type"=>"submit", "name"=>"btnUpload", "value"=>t("Upload"));
            $fields[] = array("type"=>"submit", "name"=>"btnCancel", "value"=>t("Cancel"));

            $fieldset[] = array("fields"=>$fields);

            print JarisCMS\Form\Generate($parameters, $fieldset);

        ?>
    field;

    field: is_system
        1
    field;
row;
